github:
  bucket:
    # 配置仓库所属的用户名（如果是自己创建的，就是自己的用户名）
    user: "xiuyuandashen"
    # 配置仓库名称
    repository: "figureBed"
    # 配置自己的acccessToken
    access-token: "99d9d2897c6a8124b95836dc585e99d1bd196973"
    url: "https://cdn.jsdelivr.net/gh/${github.bucket.user}/${github.bucket.repository}/"
    api: "https://api.github.com/repos/${github.bucket.user}/${github.bucket.repository}/contents/"